#!/usr/bin/env python3
"""
USBIP Server Configuration Generator

This script parses the Kconfig file and generates compile definitions.
Similar to Linux kernel configuration.

Usage:
    python scripts/gen_config.py

Design:
1. Parse Kconfig for default values
2. Load existing .config if present (user overrides)
3. Merge: defaults overridden by user config
4. Generate build/config.cmake with -D definitions for compiler
5. Generate .config file for reference
"""

import os
import re
import sys
from pathlib import Path

# Project root (assumes script is in scripts/ directory)
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
KCONFIG_PATH = PROJECT_ROOT / "Kconfig"
CONFIG_FILE_PATH = PROJECT_ROOT / ".config"
CMAKE_CONFIG_PATH = PROJECT_ROOT / "build" / "config.cmake"

# Log level mapping
LOG_LEVELS = {
    0: "LOG_LEVEL_NONE",
    1: "LOG_LEVEL_ERR",
    2: "LOG_LEVEL_WRN",
    3: "LOG_LEVEL_INF",
    4: "LOG_LEVEL_DBG",
}


def parse_kconfig(kconfig_path):
    """
    Parse Kconfig file and extract default configuration values.

    Returns:
        dict: Configuration name -> default value
    """
    defaults = {}

    if not kconfig_path.exists():
        print(f"Error: Kconfig file not found: {kconfig_path}")
        sys.exit(1)

    with open(kconfig_path, 'r') as f:
        lines = f.readlines()

    current_config = None

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Match config name
        if stripped.startswith("config "):
            match = re.match(r'config\s+(\w+)', stripped)
            if match:
                current_config = match.group(1)

        # Match default value
        elif stripped.startswith("default ") and current_config:
            value = stripped.split()[1]
            # Skip if it's a string value (quoted)
            if not value.startswith('"'):
                defaults[current_config] = value
                current_config = None

        # Reset current_config if we hit other keywords
        elif stripped.startswith("help") or stripped.startswith("menu") or stripped.startswith("endmenu"):
            current_config = None

    return defaults


def load_config_file(config_path):
    """
    Load existing .config file (Linux-style).

    Returns:
        dict: Configuration name -> value
    """
    config = {}

    if not config_path.exists():
        return config

    with open(config_path, 'r') as f:
        for line in f:
            line = line.strip()

            # Skip comments and empty lines
            if not line or line.startswith('#'):
                continue

            # Parse CONFIG_NAME=value
            if '=' in line:
                name, value = line.split('=', 1)

                # Check for "# CONFIG_NAME is not set" (Linux style)
                if name.startswith('CONFIG_'):
                    key = name[7:]  # Remove CONFIG_ prefix
                    if value == '' or value == 'is not set':
                        # Remove the config (use default)
                        if key in config:
                            del config[key]
                    else:
                        config[key] = value

    return config


def save_config_file(config, config_path):
    """
    Save configuration to .config file (Linux-style).

    Args:
        config: Dictionary of config values
        config_path: Path to write .config
    """
    with open(config_path, 'w') as f:
        f.write("#\n")
        f.write("# .config - USBIP Server Configuration\n")
        f.write("#\n")
        f.write("# Generated by scripts/gen_config.py\n")
        f.write("#\n")
        f.write("# Configuration:\n")
        f.write("#   Edit this file to override default values\n")
        f.write("#   Then run: python scripts/gen_config.py\n")
        f.write("#\n")
        f.write("\n")

        for key, value in sorted(config.items()):
            f.write(f"CONFIG_{key}={value}\n")

    print(f"Generated config: {config_path}")


def generate_cmake_config(config, output_path):
    """
    Generate CMake config file with compile definitions.

    Args:
        config: Dictionary of config values
        output_path: Path to write config.cmake
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        f.write("#\n")
        f.write("# config.cmake - USBIP Server Build Configuration\n")
        f.write("#\n")
        f.write("# Generated by scripts/gen_config.py\n")
        f.write("# Do not edit manually\n")
        f.write("#\n")
        f.write("\n")

        # Generate compile definitions for all config options
        for key, value in sorted(config.items()):
            # Skip string values (quoted in Kconfig)
            if value.startswith('"'):
                continue

            # Regular config - just pass the value
            f.write(f"add_compile_definitions(CONFIG_{key}={value})\n")

    print(f"Generated config: {output_path}")


def merge_config(defaults, user_config):
    """
    Merge user config with defaults.
    User config values override defaults.

    Args:
        defaults: Dictionary of default values from Kconfig
        user_config: Dictionary of user override values from .config

    Returns:
        dict: Merged configuration
    """
    # Start with defaults
    merged = dict(defaults)

    # Override with user config
    for key, value in user_config.items():
        merged[key] = value

    return merged


def print_config_diff(defaults, merged):
    """Print configuration changes from defaults."""
    changed = False

    for key, value in sorted(merged.items()):
        default_value = defaults.get(key)
        if default_value != value:
            print(f"  {key}: {default_value} -> {value}")
            changed = True

    if not changed:
        print("  (using all default values)")


def main():
    """Main entry point."""
    print("USBIP Server Configuration Generator")
    print("=" * 40)
    print(f"Kconfig: {KCONFIG_PATH}")
    print(f"User config: {CONFIG_FILE_PATH}")
    print(f"CMake config: {CMAKE_CONFIG_PATH}")
    print()

    # Parse Kconfig for defaults
    print("Reading Kconfig defaults...")
    defaults = parse_kconfig(KCONFIG_PATH)

    if not defaults:
        print("Warning: No configuration found in Kconfig")
        return

    # Load user config if exists
    print("Loading user configuration...")
    user_config = load_config_file(CONFIG_FILE_PATH)

    if user_config:
        print("  Found user configuration, merging...")
    else:
        print("  No user configuration found, using defaults")

    # Merge configurations
    config = merge_config(defaults, user_config)

    # Print what changed
    if user_config:
        print("\nConfiguration changes from defaults:")
        print_config_diff(defaults, config)

    # Generate config files
    print("\nGenerating configuration files...")

    # Save .config (so user can see current settings)
    save_config_file(config, CONFIG_FILE_PATH)

    # Generate CMake config
    generate_cmake_config(config, CMAKE_CONFIG_PATH)

    print("\nDone!")
    print()
    print("To configure:")
    print(f"  1. Edit {CONFIG_FILE_PATH}")
    print("  2. Run: python scripts/gen_config.py")
    print("  3. Rebuild: cmake --build build")
    print()
    print("To reset to defaults:")
    print(f"  1. Delete {CONFIG_FILE_PATH}")
    print("  2. Run: python scripts/gen_config.py")


if __name__ == "__main__":
    main()